name = "grady-bot"
compatibility_date = "2024-09-09"
compatibility_flags = [ "nodejs_compat" ]


[triggers]
crons = ["0 6 * * *", "0 7-20/1 * * *"]

[vars]
NODE_ENV = "prod"

[observability]
enabled = true